services:
  mysql-product:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - product-data:/var/lib/mysql

  mysql-order:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - order-data:/var/lib/mysql

  postgres-user:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

volumes:
  product-data:
  order-data:
  user-data: