services:
  mysql-product:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - product-data:/var/lib/mysql

  mysql-order:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - order-data:/var/lib/mysql

  mysql-cart:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - cart-data:/var/lib/mysql

  postgres-user:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  mongo-review:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: review_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - review-data:/data/db

  mongo-discount:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: discount_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - discount-data:/data/db

  mongo-payment:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: payment_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27019:27017"
    volumes:
      - payment-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # message broker port
      - "15672:15672" # ui port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  product-data:
  order-data:
  cart-data:
  user-data:
  review-data:
  discount-data:
  payment-data:
  rabbitmq-data: